
    defn soft_reset,         0x00

    defn hard_reset,         0x26

    defn halt,               0x02

    defn stop,               0x03

    defn wait_for_interrupt, 0x04

    defn wait_for_vblank,    0x05

    defn div_mod,            0x06

    defn div_mod_arm,        0x07

    defn sqrt,               0x08

    defn arc_tan,            0x09

    defn arc_tan2,           0x0A

    defn cpu_set,            0x0B

    defn cpu_fast_set,       0x0C

    defn get_bios_checksum,  0x0D

    defn bg_affine_set,      0x0E

    defn obj_affine_set,     0x0F
